platform :ios, '11.3'

target 'MySafe' do
  use_frameworks!
end

#Uncomment the bellow target for dependecies for tests
#target 'MySafeTests' do 
#  use_frameworks!
#end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
