platform :ios, '11.3'

target 'MySafe' do
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'SwiftKeychainWrapper'
  pod 'Kingfisher', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
end

target 'MySafeTests' do 
  use_frameworks!
  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
